
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 21 23:40:04 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 14;
  public static final int LTE = 37;
  public static final int LBRACKET = 31;
  public static final int CONST = 17;
  public static final int NAMESPACE = 23;
  public static final int NUMCONST = 32;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 18;
  public static final int FOR = 44;
  public static final int MINUS = 35;
  public static final int STATIC = 43;
  public static final int RPAREN = 7;
  public static final int AND = 33;
  public static final int LT = 39;
  public static final int OR = 16;
  public static final int COMMA = 8;
  public static final int CLASS = 22;
  public static final int INC = 25;
  public static final int PLUS = 11;
  public static final int IF = 50;
  public static final int ASSIGN = 36;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 24;
  public static final int EQUAL = 12;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int PROGRAM = 21;
  public static final int NUMBER = 46;
  public static final int MOD = 30;
  public static final int NEQ = 20;
  public static final int IDENT = 49;
  public static final int BREAK = 28;
  public static final int VOID = 13;
  public static final int EQ = 19;
  public static final int GTE = 40;
  public static final int TIMES = 29;
  public static final int ARROW = 34;
  public static final int COLON = 45;
  public static final int ELSE = 51;
  public static final int LBRACE = 3;
  public static final int READ = 26;
  public static final int CHARCONST = 48;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 42;
  public static final int PROG = 2;
  public static final int DEC = 15;
  public static final int GT = 27;
  public static final int PRINT = 9;
}

